[package]
name = "sams_calc_rust"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 2

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
